### ISSUE TITLE
Feature Request: ability to select data source

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [Riathoir/PASSGAN-IWGAN-Tensorflow-2#14]
Currently you're only able to use the rock_you dataset predefined by the DatasetPipeline. It would be nice to see the ability to load a dataset based on a specified file such as a rock_you source hosted locally.

**Comment by Riathoir** [comment]
Hi,
You're welcome to define a different dataset stored in tf.pipelines using the set flag, how it'll handle non-text datasets is a mystery although I imagine it'll probably be fine as it converts everything to an integer value for speed regardless.

In regards to local datasets that would indeed be a good feature. It is possible through tf.data framework and pandas: https://medium.com/deep-learning-with-keras/tf-data-build-efficient-tensorflow-input-pipelines-for-image-datasets-47010d2e4330

I have no plans to maintain this code base as I'm not actively working on it - partly due to time and partly due to selling my gpu during the price uptick. Stonks.
But I'll keep it in mind and will review a merge request if you'd like it added.

Thanks,
Rachel
